### ISSUE TITLE
plexidrive.sh shouldn't run if the script is already being executed

### ISSUE THREAD

**Issue by olipayne** [masonr/PLEXiDRIVE#1]
If plexidrive.sh checks to see if it's already running before executing, it would mean we can have a relatively frequent cronjob schedule.

**Comment by masonr** [comment]
Agreed. I'll add that in shortly and update this issue when done.

**Comment by masonr** [comment]
Fixed with commit 23fdebb. Added check at beginning of plexidrive.sh to ensure script is not already running.

**Comment by masonr** [comment]
Scratch that last commit. Reopening this issue and reverting the last commit as it prevents the script from being ran at all. Needs further investigation.

**Comment by olipayne** [comment]
Yeah I see that too, however I'm not sure why it doesnt work with an `if [ "$precheck" -gt 2 ] ; then`
Since the script is already running at the time of the check, the count should be exactly 2.

**Comment by masonr** [comment]
Yeah, the issue with that is I typically run the script with screen. So it'll count the screen instance and the actual script running so the count will already be at 2 when running the script once. I'll look into finding another way to detect that the script is already running.

**Comment by olipayne** [comment]
PR incoming, give me a few mins

**Comment by masonr** [comment]
Thanks for sorting this one out.
