### ISSUE TITLE
./plexidrive.sh only prints file name

### ISSUE THREAD

**Issue by Tawmmm** [masonr/PLEXiDRIVE#3]
Hey,

I've setup your scripts as per your instructions and ran through them several times to make sure I haven't made a mistake, however when I run ./plexidrive.sh the only output I get is
root@cheesus ~/PLEXiDRIVE # ./plexidrive.sh
File: Quantico - S02E21 - RAINBOW HDTV-720p.mkv

Doesn't seem to process or upload the file at all, anything obvious I've done wrong, or anywhere I can find some logs to see what's up?

I can do gdrive list which shows my gdrive files so that connects fine, and I have rclone mounting the gdrive fine.

Thanks!

**Comment by masonr** [comment]
You can check the 'upload-error' file, which should have any errors that have occurred during uploads. Also, double check the "gdrive_config_paths" variable in your 'plexidrive.conf' file -- make sure it's an absolute path and that it actually exists.

Let me know what you find!
-Mason

**Comment by Tawmmm** [comment]
Aaaaand I feel dumb, it was the gdrive_config_paths small typo!

Thanks a lot for your help and great set of scripts! Just 1 more question, I've recently moved all my media over from ACD to google drive, do you have any suggestions for how I can get plex to scan all the existing data without getting 24 hour banned?

Thanks!

**Comment by masonr** [comment]
It's always the little things! :)

Absolutely! You have one of two options that I can think of.
1. Easiest method - You bite the bullet and rescan the whole library (probably getting a 24-hour ban)
2. Harder method - Take an _ls_ of your Movie and TV Show directories and write each output to a file. Depending on how much media you have, you can either write a script or add by hand the prefixes (i.e. "tv:tv_show_name" or "mov:movie_name"). Then copy over 10 or 20 lines at a time to the _plex_scan_ file and run the scanner every hour or two.

If it were me, I'd probably just do the auto scan and watch netflix or what have you for the next day until the ban is gone. But, that's ultimately up to you.

Good luck!,
-Mason

**Comment by Tawmmm** [comment]
Alright bud thanks! I managed to scan all my movies before getting 403s, TV tomorrow I guess!

Thanks for your help!

**Comment by masonr** [comment]
Forgot another option you could try. If the directory structure is the same between your ACD and Drive mount, you could also try to just symlink the old mount path to the new mount path.

For example, if your old mount path for tv shows was:
/mnt/acd/TV Shows
and your new mount path is:
/mnt/drive/TV Shows

You could just create a symlink from /mnt/acd to /mnt/drive and you wouldn't even need to rescan anything.

Edit: Just read your latest message. Sounds good.

**Comment by Tawmmm** [comment]
I did consider that, but decided to just start from scratch with a slightly different setup anyway.

The way I did TV was as you suggested, adding the folders to plex-scan a dozen at a time and running the scan.  I used the google script below to list all the folders in a google sheet and reformatted it to match the tv:series:season x: format.

```
// Set folder ID
var folderId = 'ID HERE';
 
// List all folders, & write into the current sheet.
function listFolders(){
  getFolderTree(folderId, false);
};
```
