### ISSUE TITLE
cannot fetch to ken: 400 Bad Request

### ISSUE THREAD

**Issue by goodpunk6** [masonr/PLEXiDRIVE#7]
When I run this - 

`> ~$ gdrive --config ~/.gdrive-main about`

I get - 

```
gdrive --config ~/.gdrive-main about
Failed to get about: Get https://www.googleapis.com/drive/v3/about?alt=json&fields=maxImportSizes%2CmaxUploadSize%2CstorageQuota%2Cuser: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error" : "invalid_grant"
}

[1]+  Stopped                 sudo rclone mount --allow-non-empty --allow-other the_matrix:/ /mnt/gdrive-main

```

Please not sure what to do. Anyone else having this issue?

**Comment by masonr** [comment]
Strange that running the gdrive command stops your rclone mount.

I'd suggest following the little guide here: https://rclone.org/drive/#making-your-own-client-id. And create your own client id / secret key for both rclone and gdrive. Then remove the gdrive token and the rclone config for the drive account and reconnect using the new id's.

Let me know how it goes.

**Comment by goodpunk6** [comment]
How do I remove the token?

**Comment by masonr** [comment]
For rclone, when you run the `rclone config` command, there's an option to delete an entry.

For gdrive, simply delete the _token_v2.json_ file in your config directory (i.e. ~/.gdrive-main/token_v2.json).

**Comment by goodpunk6** [comment]
I don't see any json file in the /mnt/gdrive-main directory. I'll delete
the entry for rclone

**Comment by masonr** [comment]
It wouldn't be in your mounted directory. It'd be in your gdrive config directory within your home directory. Might have to do a `ls -a` to see it. There will be a token json file in there.

**Comment by goodpunk6** [comment]
Awesome. I removed it and will do the rest in the AM. I need sleep

**Comment by goodpunk6** [comment]
Ok curiosity got me. That worked like a charm. Thanks for the help!!

**Comment by masonr** [comment]
Excellent! I'm glad it worked out. Let me know if you run into any other issues.
